## SCANLINES
default:
  # libretro
  shader: crt/GritsScanlines
  # emulators using reshader 
  m2emulator: ScanlinesAbs@scanlines-abs.fx
  supermodel: ScanlinesAbs@scanlines-abs.fx
  hypseus: ScanlinesAbs@scanlines-abs.fx
  daphne: ScanlinesAbs@scanlines-abs.fx
  oricutron: ScanlinesAbs@scanlines-abs.fx
  applewin: ScanlinesAbs@scanlines-abs.fx
  gsplus: ScanlinesAbs@scanlines-abs.fx
  mednafen: ScanlinesAbs@scanlines-abs.fx
  scummvm: ScanlinesAbs@scanlines-abs.fx
  simcoupe: ScanlinesAbs@scanlines-abs.fx 
  demul: ScanlinesAbs@scanlines-abs.fx
  phoenix: ScanlinesAbs@scanlines-abs.fx
  bigpemu: ScanlinesAbs@scanlines-abs.fx
n64:
  shader: interpolation/sharp-bilinear-scanlines
gba:
  shader: handheld/lcd-grid-v2
gb:
  shader: handheld/lcd-grid-v2
gb2players:
  shader: handheld/lcd-grid-v2
gbc:
  shader: handheld/lcd-grid-v2
gbc2players:
  shader: handheld/lcd-grid-v2
nds:
  shader: handheld/lcd-grid-v2-nds-color
3ds:
  shader: handheld/lcd-shader
virtualboy:
  shader: retro/sharp-bilinear-scanlines
gc:
  shader: anti-aliasing/fxaa
wii:
  shader: anti-aliasing/fxaa
dreamcast:
  shader: anti-aliasing/fxaa
gamegear:
  shader: handheld/lcd-grid-v2
ngp:
  shader: handheld/lcd-grid-v2
ngpc:
  shader: handheld/lcd-grid-v2
gw:
  shader: handheld/lcd-grid-v2
lynx:
  shader: handheld/lcd-grid-v2
wswan:
  shader: handheld/lcd-grid-v2
wswanc:
  shader: handheld/lcd-grid-v2
psp:
  shader: handheld/lcd-grid-v2
