github: [TheDayG0ne, PRO100BYTE, PRO100BYTE-Helper]
custom: ["https://www.donationalerts.com/r/projectarcade", "https://www.donationalerts.com/r/tdglive", "https://tips.yandex.ru/guest/payment/7477970"]
