## FLATTEN GLOW
default:
  # shader affects retroarch shaders
  shader: blurs/kawase_glow
  # scanline affect fba2x
  scanline: true
# Reshader  
model2:
  shader: disabled
model3:
  shader: disabled  
# Nintendo
gba:
  shader: handheld/simpletex_lcd+gba-color
gb:
  shader: handheld/simpletex_lcd
gb2players:
  shader: handheld/simpletex_lcd
gbc:
  shader: handheld/simpletex_lcd+gbc-color
gbc2players:
  shader: handheld/simpletex_lcd+gbc-color
3ds:
  shader: handheld/simpletex_lcd
nds:
  shader: handheld/simpletex_lcd
virtualboy:
  shaderGL: interpolation/sharp-bilinear-scanlines
  shader: pixel-art-scaling/sharp-bilinear-scanlines
# Sega
gamegear:
  shader: handheld/simpletex_lcd+gbc-color
#
ngp:
  shader: handheld/simpletex_lcd
ngpc:
  shader: handheld/simpletex_lcd
lynx:
  shader: handheld/simpletex_lcd+gbc-color
wswan:
  shader: handheld/simpletex_lcd
wswanc:
  shader: handheld/simpletex_lcd+gbc-color
psp:
  shader: handheld/lcd-grid-v2-psp-color
