## FLATTEN GLOW
default:
  # shader affects retroarch shaders
  shader: blurs/kawase_glow
  # scanline affect fba2x
  scanline: true
# Reshader  
model2:
  shader: disabled
model3:
  shader: disabled  
# Nintendo
snes:
  shader: blurs/kawase_glow
snes-msu:
  shader: blurs/kawase_glow
nes:
  shader: blurs/kawase_glow
n64:
  shader: blurs/kawase_glow
satellaview:
  shader: blurs/kawase_glow
sufami:
  shader: blurs/kawase_glow
gba:
  shader: handheld/simpletex_lcd+gba-color
gb:
  shader: handheld/simpletex_lcd
gb2players:
  shader: handheld/simpletex_lcd
gbc:
  shader: handheld/simpletex_lcd+gbc-color
gbc2players:
  shader: handheld/simpletex_lcd+gbc-color
3ds:
  shader: handheld/simpletex_lcd_darker
nds:
  shader: handheld/simpletex_lcd_darker
fds:
  shader: blurs/kawase_glow
virtualboy:
  shader: retro/sharp-bilinear-scanlines
gc:
  shader: blurs/kawase_glow
wii:
  shader: blurs/kawase_glow
# Sega
dreamcast:
  shader: anti-aliasing/smaa
sg1000:
  shader: blurs/kawase_glow
mastersystem:
  shader: blurs/kawase_glow
megadrive:
  shader: blurs/kawase_glow
gamegear:
  shader: handheld/simpletex_lcd+gbc-color
sega32x:
  shader: blurs/kawase_glow
segacd:
  shader: blurs/kawase_glow
saturn:
  shader: blurs/kawase_glow
# Arcade
neogeo:
  shader: blurs/kawase_glow
neogeocd:
  shader: blurs/kawase_glow
mame:
  shader: blurs/kawase_glow
fba:
  shader: blurs/kawase_glow
naomi:
  shader: blurs/kawase_glow
atomiswave:
  shader: blurs/kawase_glow
#
3do:
  shader: blurs/kawase_glow
ngp:
  shader: handheld/simpletex_lcd
ngpc:
  shader: handheld/simpletex_lcd
gw:
  shader: blurs/kawase_glow
vectrex:
  shader: blurs/kawase_glow
lynx:
  shader: handheld/simpletex_lcd+gbc-color
lutro:
  shader: blurs/kawase_glow
wswan:
  shader: handheld/simpletex_lcd
wswanc:
  shader: handheld/simpletex_lcd+gbc-color
pcengine:
  shader: blurs/kawase_glow
pcenginecd:
  shader: blurs/kawase_glow
supergrafx:
  shader: blurs/kawase_glow
atari800:
  shader: blurs/kawase_glow
atari2600:
  shader: blurs/kawase_glow
atari5200:
  shader: blurs/kawase_glow
atari7800:
  shader: blurs/kawase_glow
prboom:
  shader: blurs/kawase_glow
psx:
  shader: blurs/kawase_glow
ps2:
  shader: blurs/kawase_glow
psp:
  shader: handheld/lcd-grid-v2-psp-color
colecovision:
  shader: blurs/kawase_glow
jaguar:
  shader: blurs/kawase_glow
lightgun:
  shader: blurs/kawase_glow
# Computers
lutro:
  shader: blurs/kawase_glow
msx:
  shader: blurs/kawase_glow
msx1:
  shader: blurs/kawase_glow
msx2:
  shader: blurs/kawase_glow
amiga:
  shader: blurs/kawase_glow
amiga1200:
  shader: blurs/kawase_glow
amiga500:
  shader: blurs/kawase_glow
amigacd32:
  shader: blurs/kawase_glow
amigacdtv:
  shader: blurs/kawase_glow
c20:
  shader: blurs/kawase_glow
c64:
  shader: blurs/kawase_glow
c128:
  shader: blurs/kawase_glow
cave:
  shader: blurs/kawase_glow
cps1:
  shader: blurs/kawase_glow
cps3:
  shader: blurs/kawase_glow
dos:
  shader: blurs/kawase_glow
amstradcpc:
  shader: blurs/kawase_glow
atarist:
  shader: blurs/kawase_glow
zx81:
  shader: blurs/kawase_glow
zxspectrum:
  shader: blurs/kawase_glow
odyssey2:
  shader: blurs/kawase_glow
zx81:
  shader: blurs/kawase_glow
pcfx:
  shader: blurs/kawase_glow
x68000:
  shader: blurs/kawase_glow
o2em:
  shader: blurs/kawase_glow
scummvm:
  shader: blurs/kawase_glow
pc98:
  shader: blurs/kawase_glow
pcfx:
  shader: blurs/kawase_glow
thomson:
  shader: blurs/kawase_glow
