[Input]
useSpecialPad = false
cursorState = 1
cursorHideTimeout = 5
backButtonBehavior = "left"
specialPadClass = 1

[General]
isPS4Pro = false
BGMvolume = 50
logFilter = ""
playBGM = false
Fullscreen = false
isTrophyPopupDisabled = false
enableDiscordRPC = false
logType = "async"
userName = "RetroBat"
updateChannel = "Release"
showSplash = false
autoUpdate = false
separateUpdateEnabled = true
compatibilityEnabled = true
checkCompatibilityOnStartup = false

[GPU]
dumpShaders = false
screenWidth = 800
vblankDivider = 1
screenHeight = 600
nullGpu = false
patchShaders = true
copyGPUBuffers = false

[Vulkan]
validation_sync = false
gpuId = -1
validation = false
crashDiagnostic = false
validation_gpu = false
rdocEnable = false
rdocMarkersEnable = false

[Settings]
consoleLanguage = 2

[GUI]
installDirs = []
addonInstallDir = ""
emulatorLanguage = "en"
mw_width = 1280
theme = 0
mw_height = 720
iconSize = 36
sliderPos = 0
iconSizeGrid = 69
sliderPosGrid = 0
geometry_x = 400
gameTableMode = 0
pkgDirs = []
geometry_y = 400
geometry_w = 1280
geometry_h = 720
elfDirs = []
recentFiles = []

[Debug]
DebugDump = false
CollectShader = false

