## ENHANCED
default:
  # libretro
  shader: hqx/hq2x
  # emulators using reshader 
  mednafen: HQ4X@HQ4X.fx
  m2emulator: HQ4X@HQ4X.fx
  supermodel: HQ4X@HQ4X.fx
  hypseus: HQ4X@HQ4X.fx
  daphne: HQ4X@HQ4X.fx
  oricutron: HQ4X@HQ4X.fx
  applewin: HQ4X@HQ4X.fx
  gsplus: HQ4X@HQ4X.fx  
  scummvm: HQ4X@HQ4X.fx  
  simcoupe: HQ4X@HQ4X.fx  
  demul: HQ4X@HQ4X.fx
  phoenix: HQ4X@HQ4X.fx
  bigpemu: HQ4X@HQ4X.fx  
# per system overrides  
n64:
  shader: anti-aliasing/fxaa
gba:
  shader: handheld/lcd-grid-v2-gba-color
gb:
  shader: handheld/gameboy
gb2players:
  shader: handheld/gameboy
gbc:
  shader: handheld/lcd-grid-v2-gbc-color
gbc2players:
  shader: handheld/lcd-grid-v2-gbc-color
nds:
  shader: handheld/lcd-grid-v2-nds-color
3ds:
  shader: handheld/lcd-shader
virtualboy:
  shader: retro/sharp-bilinear-scanlines
gc:
  shader: anti-aliasing/fxaa
wii:
  shader: anti-aliasing/fxaa
# Sega
dreamcast:
  shader: anti-aliasing/enhanced-fxaa-tvout
gamegear:
  shader: crt-guest-dr-venom-fast
saturn:
  shader: anti-aliasing/fxaa
# Arcade
naomi:
  shader: anti-aliasing/fxaa
# Misc
ngp:
  shader: handheld/gameboy
ngpc:
  shader: handheld/lcd-grid-v2-gbc-color
gw:
  shader: handheld/gameboy
lynx:
  shader: crt-guest-dr-venom-fast
wswan:
  shader: handheld/gameboy
wswanc:
  shader: handheld/lcd-grid-v2-gbc-color
psx:
  shader: anti-aliasing/fxaa
ps2:
  shader: anti-aliasing/fxaa
psp:
  shader: handheld/lcd-grid-v2-psp-color
