## ENHANCED
default:
  # libretro
  shaderGL: hqx/hq2x
  shader: edge-smoothing/hqx/hq2x
  # emulators using reshader 
  mednafen: HQ4X@HQ4X.fx
  m2emulator: HQ4X@HQ4X.fx
  supermodel: HQ4X@HQ4X.fx
  hypseus: HQ4X@HQ4X.fx
  daphne: HQ4X@HQ4X.fx
  oricutron: HQ4X@HQ4X.fx
  applewin: HQ4X@HQ4X.fx
  gsplus: HQ4X@HQ4X.fx  
  scummvm: HQ4X@HQ4X.fx  
  simcoupe: HQ4X@HQ4X.fx  
  demul: HQ4X@HQ4X.fx
  phoenix: HQ4X@HQ4X.fx
  bigpemu: HQ4X@HQ4X.fx
  demul: HQ4X@HQ4X.fx
  demul-old: HQ4X@HQ4X.fx
  solarus: HQ4X@HQ4X.fx
  redream: HQ4X@HQ4X.fx
  raine: HQ4X@HQ4X.fx
  duckstation: HQ4X@HQ4X.fx
  mupen64: HQ4X@HQ4X.fx
  xemu: HQ4X@HQ4X.fx
# per system overrides  
n64:
  shader: anti-aliasing/fxaa
gba:
  shader: handheld/lcd-grid-v2-gba-color
gb:
  shader: handheld/gameboy
gb2players:
  shader: handheld/gameboy
gbc:
  shader: handheld/lcd-grid-v2-gbc-color
gbc2players:
  shader: handheld/lcd-grid-v2-gbc-color
nds:
  shader: handheld/lcd-grid-v2-nds-color
3ds:
  shader: handheld/lcd-shader
virtualboy:
  shaderGL: interpolation/sharp-bilinear-scanlines
  shader: pixel-art-scaling/sharp-bilinear-scanlines
gc:
  shader: anti-aliasing/fxaa
wii:
  shader: anti-aliasing/fxaa
# Sega
dreamcast:
  shader: anti-aliasing/fxaa
  redream: HQ4X@HQ4X.fx
gamegear:
  shaderGL: crt/crt-guest-dr-venom-fast
  shader: crt/crt-guest-advanced-fast
saturn:
  shader: anti-aliasing/fxaa
  mednafen: HQ4X@HQ4X.fx
# Arcade
naomi:
  shader: anti-aliasing/fxaa
# Misc
ngp:
  shader: handheld/gameboy
ngpc:
  shader: handheld/lcd-grid-v2-gbc-color
gw:
  shader: handheld/gameboy
lynx:
  shaderGL: crt/crt-guest-dr-venom-fast
  shader: crt/crt-guest-advanced-fast
  mednafen: HQ4X@HQ4X.fx
wswan:
  shader: handheld/gameboy
  mednafen: HQ4X@HQ4X.fx
wswanc:
  shader: handheld/lcd-grid-v2-gbc-color
  mednafen: HQ4X@HQ4X.fx
psx:
  shader: anti-aliasing/fxaa
  mednafen: HQ4X@HQ4X.fx
ps2:
  shader: anti-aliasing/fxaa
psp:
  shader: handheld/lcd-grid-v2-psp-color
