## RETRO
default:
  # shader affects retroarch shaders
  shader: interpolation/sharp-bilinear-simple
  # scanline affect fba2x
  scanline: true
# Reshader  
model2:
  shader: disabled
model3:
  shader: disabled  
# Nintendo
snes:
  shader: interpolation/sharp-bilinear-simple
snes-msu:
  shader: interpolation/sharp-bilinear-simple
nes:
  shader: interpolation/sharp-bilinear-simple
n64:
  shader: interpolation/sharp-bilinear-simple
satellaview:
  shader: interpolation/sharp-bilinear-simple
sufami:
  shader: interpolation/sharp-bilinear-simple
gba:
  shader: handheld/bevel
gb:
  shader: handheld/bevel
gb2players:
  shader: handheld/bevel
gbc:
  shader: handheld/bevel
gbc2players:
  shader: handheld/bevel
3ds:
  shader: reshade/nds
nds:
  shader: reshade/nds
fds:
  shader: interpolation/sharp-bilinear-simple
virtualboy:
  shader: retro/sharp-bilinear-scanlines
gc:
  shader: anti-aliasing/fxaa
wii:
  shader: anti-aliasing/fxaa
# Sega
dreamcast:
  shader: anti-aliasing/fxaa
sg1000:
  shader: interpolation/sharp-bilinear-simple
mastersystem:
  shader: interpolation/sharp-bilinear-simple
megadrive:
  shader: interpolation/sharp-bilinear-simple
gamegear:
  shader: handheld/simpletex_lcd+gbc-color
sega32x:
  shader: interpolation/sharp-bilinear-simple
segacd:
  shader: interpolation/sharp-bilinear-simple
saturn:
  shader: interpolation/sharp-bilinear-simple
# Arcade
neogeo:
  shader: interpolation/sharp-bilinear-simple
neogeocd:
  shader: interpolation/sharp-bilinear-simple
mame:
  shader: interpolation/sharp-bilinear-simple
fba:
  shader: interpolation/sharp-bilinear-simple
naomi:
  shader: interpolation/sharp-bilinear-simple
atomiswave:
  shader: interpolation/sharp-bilinear-simple
#
3do:
  shader: interpolation/sharp-bilinear-simple
ngp:
  shader: handheld/bevel
ngpc:
  shader: handheld/bevel
gw:
  shader: interpolation/sharp-bilinear-simple
vectrex:
  shader: interpolation/sharp-bilinear-simple
lynx:
  shader: handheld/bevel
lutro:
  shader: interpolation/sharp-bilinear-simple
wswan:
  shader: handheld/bevel
wswanc:
  shader: handheld/bevel
pcengine:
  shader: interpolation/sharp-bilinear-simple
pcenginecd:
  shader: interpolation/sharp-bilinear-simple
supergrafx:
  shader: interpolation/sharp-bilinear-simple
atari800:
  shader: interpolation/sharp-bilinear-simple
atari2600:
  shader: interpolation/sharp-bilinear-simple
atari5200:
  shader: interpolation/sharp-bilinear-simple
atari7800:
  shader: interpolation/sharp-bilinear-simple
prboom:
  shader: interpolation/sharp-bilinear-simple
psx:
  shader: interpolation/sharp-bilinear-simple
ps2:
  shader: interpolation/sharp-bilinear-simple
psp:
  shader: handheld/bevel
colecovision:
  shader: interpolation/sharp-bilinear-simple
jaguar:
  shader: interpolation/sharp-bilinear-simple
lightgun:
  shader: interpolation/sharp-bilinear-simple
# Computers
lutro:
  shader: interpolation/sharp-bilinear-simple
msx:
  shader: interpolation/sharp-bilinear-simple
msx1:
  shader: interpolation/sharp-bilinear-simple
msx2:
  shader: interpolation/sharp-bilinear-simple
amiga:
  shader: interpolation/sharp-bilinear-simple
amiga1200:
  shader: interpolation/sharp-bilinear-simple
amiga500:
  shader: interpolation/sharp-bilinear-simple
amigacd32:
  shader: interpolation/sharp-bilinear-simple
amigacdtv:
  shader: interpolation/sharp-bilinear-simple
c20:
  shader: interpolation/sharp-bilinear-simple
c64:
  shader: interpolation/sharp-bilinear-simple
c128:
  shader: interpolation/sharp-bilinear-simple
cave:
  shader: interpolation/sharp-bilinear-simple
cps1:
  shader: interpolation/sharp-bilinear-simple
cps3:
  shader: interpolation/sharp-bilinear-simple
dos:
  shader: interpolation/sharp-bilinear-simple
amstradcpc:
  shader: interpolation/sharp-bilinear-simple
atarist:
  shader: interpolation/sharp-bilinear-simple
zx81:
  shader: interpolation/sharp-bilinear-simple
zxspectrum:
  shader: interpolation/sharp-bilinear-simple
odyssey2:
  shader: interpolation/sharp-bilinear-simple
zx81:
  shader: interpolation/sharp-bilinear-simple
pcfx:
  shader: interpolation/sharp-bilinear-simple
x68000:
  shader: interpolation/sharp-bilinear-simple
o2em:
  shader: interpolation/sharp-bilinear-simple
scummvm:
  shader: interpolation/sharp-bilinear-simple
pc98:
  shader: interpolation/sharp-bilinear-simple
pcfx:
  shader: interpolation/sharp-bilinear-simple
thomson:
  shader: interpolation/sharp-bilinear-simple
