; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ProjectArcade"
#define MyAppVersion "1.5.3"
#define MyAppPublisher "#TheDayG0ne"
#define MyAppURL "https://projects.thedayg0ne.ru/projectarcade"
#define MyPublisherURL "https://thedayg0ne.ru"
#define MyAppExeName "projectarcade.exe"
#define MyAppCopyright "Copyright (C) 2023 #TheDayG0ne"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B43C3830-8D79-4C32-B4C4-B29BBBAAFFCE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyPublisherURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppCopyright={#MyAppCopyright}
DefaultDirName=C:\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\thedayg0ne.TehnoLab\Desktop\LICENSE.txt
InfoBeforeFile=C:\Users\thedayg0ne.TehnoLab\Desktop\REQUIREMENTS.txt
UninstallDisplayIcon=D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\projectarcade.ico
WizardImageFile=C:\Users\thedayg0ne.TehnoLab\Desktop\projectarcade_wizard.bmp
WizardSmallImageFile=C:\Users\thedayg0ne.TehnoLab\Desktop\pa-headerlogo.bmp
DisableWelcomePage=no
VersionInfoVersion=1.5.3
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\thedayg0ne.TehnoLab\Desktop
OutputBaseFilename=ProjectArcade-1.5.3_setup
SetupIconFile=D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\projectarcade.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\retrobat.ini"; DestDir: "{app}"; Flags: ignoreversion; Attribs: readonly
Source: "D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\projectarcade.ini"; DestDir: "{app}"; Flags: ignoreversion; Attribs: readonly
Source: "D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\emulationstation\about.info"; DestDir: "{app}\emulationstation"; Flags: ignoreversion; Attribs: readonly
Source: "D:\ProjectArcade OS\ProjectArcade Lite\ProjectArcade 1.5.3\emulationstation\version.info"; DestDir: "{app}\emulationstation"; Flags: ignoreversion; Attribs: readonly 

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Comment: "Launch ProjectArcade"; IconFilename: "{app}\projectarcade.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Comment: "Launch ProjectArcade"; IconFilename: "{app}\projectarcade.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

