## ZFAST
default:
  # libretro
  shader: crt/zfast-crt
  # emulators using reshader 
  mednafen: EasymodeCRT@CRTEasymode.fx
  m2emulator: EasymodeCRT@CRTEasymode.fx
  supermodel: EasymodeCRT@CRTEasymode.fx
  hypseus: EasymodeCRT@CRTEasymode.fx
  daphne: EasymodeCRT@CRTEasymode.fx
  oricutron: EasymodeCRT@CRTEasymode.fx
  applewin: EasymodeCRT@CRTEasymode.fx  
  gsplus: EasymodeCRT@CRTEasymode.fx
  scummvm: EasymodeCRT@CRTEasymode.fx
  simcoupe: EasymodeCRT@CRTEasymode.fx
  bigpemu: EasymodeCRT@CRTEasymode.fx
  phoenix: EasymodeCRT@CRTEasymode.fx
  bigpemu: EasymodeCRT@CRTEasymode.fx  
# per system overrides  
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gb2players:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
gbc2players:
  shader: handheld/zfast-lcd
3ds:
  shader: handheld/zfast-lcd
nds:
  shader: handheld/zfast-lcd
gamegear:
  shader: handheld/zfast-lcd
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
lynx:
  shader: handheld/zfast-lcd
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd