## CRT-NEW-PIXIE
default:
  # libretro
  shader: crt/newpixie-crt
  # emulators using reshader 
  mednafen: CRTNewPixie@CRT-NewPixie.fx
  m2emulator: CRTNewPixie@CRT-NewPixie.fx
  supermodel: CRTNewPixie@CRT-NewPixie.fx
  hypseus: CRTNewPixie@CRT-NewPixie.fx
  daphne: CRTNewPixie@CRT-NewPixie.fx  
  oricutron: CRTNewPixie@CRT-NewPixie.fx
  applewin: CRTNewPixie@CRT-NewPixie.fx
  gsplus: CRTNewPixie@CRT-NewPixie.fx
  scummvm: CRTNewPixie@CRT-NewPixie.fx  
  simcoupe: CRTNewPixie@CRT-NewPixie.fx
  demul: CRTNewPixie@CRT-NewPixie.fx
  phoenix: CRTNewPixie@CRT-NewPixie.fx
  bigpemu: CRTNewPixie@CRT-NewPixie.fx

